version: '3.6'

services:
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    volumes:
      - ./meta_base:/metabase-data

  data_warehouse:
    image: postgres:13
    container_name: data_warehouse
    environment:
      POSTGRES_USER: data_lol
      POSTGRES_PASSWORD: data_lol
      POSTGRES_DB: data_lol_dw
    volumes:
      - dw-db-volume:/var/lib/postgresql/data
    ports:
      - '5430:5432'
    restart: always
  minio:
    image: 'bitnami/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=league-of-data-bronze,league-of-data-gold,league-of-data-silver
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio_data:/data
  jupyter:
    build: ./spark-scripts/docker/jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./spark-scripts/jupyter:/home/jovyan/work
  spark-master:
    build: ./spark-scripts/docker/spark-master
    container_name: spark-master
    volumes:
      - ./spark-scripts:/app
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

  spark-worker-1:
    build: ./spark-scripts/docker/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_HOME=/spark
      
volumes:
  dw-db-volume:

networks:
  default:
    name: lol-data
    external: false