version: '3.6'

services:
  minio:
    image: 'bitnami/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=league-of-data-raw
    ports:
      - '9000:9000'
      - '9001:9001'
  jupyter:
    build: ./spark-scripts/docker/jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./spark-scripts/jupyter:/home/jovyan/work
  spark-master:
    build: ./spark-scripts/docker/spark-master
    container_name: spark-master
    volumes:
      - ./spark-scripts:/app
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

  spark-worker-1:
    build: ./spark-scripts/docker/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_CORES=3
      - PYSPARK_PYTHON=python3
      - SPARK_WORKER_MEMORY=5G
      - SPARK_DRIVER_MEMORY=5G
      - SPARK_EXECUTOR_MEMORY=5G
      - SPARK_HOME=/spark
      
networks:
  default:
    name: lol-data
    external: false