version: '3.6'

services:
  minio:
    image: 'bitnami/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=league-of-data-raw
    ports:
      - '9000:9000'
      - '9001:9001'
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./spark-scripts/jupyter:/home/jovyan/work
  spark-master:
    build: ./spark-scripts/docker
    container_name: spark-master
    volumes:
      - ./spark-scripts:/app
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark